# Generated by Django 5.2.11 on 2026-02-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('venue_owner', 'Venue Owner'), ('user', 'User')], default='user', max_length=15),
        ),
    ]
