# Generated by Django 5.2.11 on 2026-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
